In [3]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits
digits=load_digits()

In [4]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(digits.data,digits.target,test_size=0.3)

In [6]:
lrModel=LogisticRegression(max_iter=10000)
lrModel.fit(x_train,y_train)
lrModel.score(x_test,y_test)

0.9685185185185186

In [7]:
svmModel=SVC()
svmModel.fit(x_train,y_train)
svmModel.score(x_test,y_test)

0.9907407407407407

In [8]:
rfcModel=RandomForestClassifier()
rfcModel.fit(x_train,y_train)
rfcModel.score(x_test,y_test)

0.9814814814814815

In [9]:
def get_score(model,x_train,x_test,y_train,y_test):
    model.fit(x_train,y_train)
    return model.score(x_test,y_test)

In [10]:
get_score(LogisticRegression(max_iter=10000),x_train,x_test,y_train,y_test)

0.9685185185185186

In [11]:
get_score(RandomForestClassifier(),x_train,x_test,y_train,y_test)

0.9777777777777777

In [12]:
get_score(SVC(),x_train,x_test,y_train,y_test)

0.9907407407407407

In [13]:
from sklearn.tree import DecisionTreeClassifier
dcModel=DecisionTreeClassifier()

In [14]:
get_score(DecisionTreeClassifier(),x_train,x_test,y_train,y_test)

0.8629629629629629

In [16]:
from sklearn.model_selection import KFold
kf=KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [17]:
for train_index,test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index,test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [20]:
from sklearn.model_selection import StratifiedKFold
skf=StratifiedKFold(n_splits=3)

In [32]:
score_lr=[]
score_svm=[]
score_rf=[]


for train_index,test_index in kf.split(digits.data):
    x_train,x_test,y_train,y_test=digits.data[train_index],digits.data[test_index],digits.target[train_index],digits.target[test_index]
    score_lr.append(get_score(LogisticRegression(max_iter=10000),x_train,x_test,y_train,y_test))
    score_svm.append(get_score(SVC(),x_train,x_test,y_train,y_test))
    score_rf.append(get_score(RandomForestClassifier(n_estimators=100),x_train,x_test,y_train,y_test))

In [25]:
score_lr

[0.9248747913188647, 0.9432387312186978, 0.9148580968280468]

In [26]:
score_svm

[0.9666110183639399, 0.9816360601001669, 0.9549248747913188]

In [33]:
score_rf

[0.9332220367278798, 0.9532554257095158, 0.9215358931552587]

In [34]:
from sklearn.model_selection import cross_val_score

In [35]:
cross_val_score(LogisticRegression(max_iter=10000),digits.data,digits.target)

array([0.92222222, 0.87222222, 0.94150418, 0.94150418, 0.89693593])

In [36]:
cross_val_score(SVC(),digits.data,digits.target)

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

In [37]:
cross_val_score(RandomForestClassifier(n_estimators=100),digits.data,digits.target)

array([0.93611111, 0.91111111, 0.95264624, 0.96935933, 0.92479109])